---
- hosts: all
  become: yes
  become_method: sudo
  become_user: root
  vars:
    docker_network: mynet

  tasks:
  - name: Create Prometheus User
    user:
      name: prometheus
      shell: /bin/false
      system: true
    tags: user

  - name: Create Prometheus Directory
    file:
      path: "{{ item }}"
      state: directory
      mode: 0775
      owner: santosh
#      owner: prometheus
    with_items:
      - /etc/prometheus/conf
      - /etc/prometheus/conf/rrules
      - /etc/prometheus/conf/alerts
    tags: directory
    become: true

  - name: Create prometheus.yml
    file:
      path: /etc/prometheus/prometheus.yml
      state: touch
      mode: 0775
      owner: santosh
#      owner: prometheus
    tags: directory
    become: true

  - name: Place configuration files
    copy:
      src: /home/santosh/workspace/devops/workplace/ansible/prom-core/configs/prometheus.yml
      dest: /etc/prometheus/prometheus.yml
      mode: 0775
      owner: santosh
#      owner: prometheus
    tags: file

#  - name: Create Alerts directory inside prometheus directory
#    become: yes
#    become_method: sudo
#    become_user: promethues
#    file:
#      path: /etc/prometheus/alerts
#      state: directory
#      mode: 0755
#      owner: prometheus
#    tags: directory

#  - name: Place alerts config files
#    become: yes
#    become_method: sudo
#    become_user: prometheus
#    file:
#      src: /home/santosh/workplace/ansible/prom-core/configs/alert.rules.yml
#      dest: /etc/prometheus/alerts
#      state: present
#      mode: 0755
#    tags: file


  - name: Create Data Directory for Prometheus
    file:
      path: /var/lib/prometheus
      state: directory
      mode: 0775
      owner: santosh
#      owner: prometheus
    tags: directory

  - name: Start Prometheus container
    docker_container:
      name: prometheus-core
      image: prom/prometheus
#      networks_cli_compatible: no
#      network_mode: mynet
#      networks:
#        - name: "{{ docker_network }}"
#          ipv4_address: 192.168.1.100
      user: 1001
      ports:
        - "9090:9090"
#      log_options:
#         max-size: "100m"
      volumes:
        - /etc/prometheus/prometheus.yml:/data/prometheus/prometheus.yml
#        - /data/prometheus:/data/prometheus
        - /data/prometheus:/prom/prometheus
      hostname: "prom-core"
      command: [ "--config.file=/etc/prometheus/prometheus.yml",
#                 "--storage.tsdb.retention=30d",
                 "--storage.tsdb.path=/data/prometheus"]


#  - name: Check who am I
#    become: true
#    become_method: su
#    become_user: santosh
#    command: 'whoami'
#    register: myid
#    tags: id

#  - name: My id
#    debug:
#      msg: '{{ myid }}'
#    tags: id


#  - name: Create Prometheus User
#    docker_container:
#      name: prometheus-core2
#      image: prom/prometheus
#      state: started
